### ISSUE TITLE
use without caddy?

### ISSUE THREAD

**Issue by tborychowski** [searx/searx-docker#34]
Hi, 
Firstly, thanks for creating this fantastic project.
I'd really like to enjoy using it, but I need some help with the setup.

I already have a reverse-proxy setup on my home server, that handles all my other services and certs and SSO.
I tried modifying the ports of the services in `docker-compose.yaml`, and:
- I can open the Filtron site (this is the entry point of the whole system isn't it?)
- I can search and get results
- but when I go to settings and hit "Save" - I get redirected to `https://localhost`

I tried modifying the `.env` and put the actual host (search.domain.tld) but that didn't do anything.

**Comment by ghost** [comment]
@tborychowski - I would also like to know. Please post if you get it working.

**Comment by tborychowski** [comment]
I went with a different image, as I don't need all the bells & whistles. 
Just searx & filtron. Here's my `docker-compose.yml`:
```yml
version: '3'
services:
  searx:
    image: hoellen/searx:master
    container_name: searx
    restart: unless-stopped
    networks:
      - searx
    environment:
      - BASE_URL="https://searx.domain.tld"

  filtron:
    container_name: filtron
    image: dalf/filtron
    restart: unless-stopped
    ports:
      - 3040:3040
      - 3041:3041
    networks:
      - searx
    command: -listen 0.0.0.0:3040 -api 0.0.0.0:3041 -target searx:8888
    volumes:
      - ./rules.json:/etc/filtron/rules.json:rw
    read_only: true

networks:
  searx:
```
